import React, { createContext, useContext, useEffect, useState } from 'react';

type Theme = 'dark' | 'light';
type Lang = 'en' | 'es';

interface AppContextValue {
  theme: Theme;
  setTheme: (t: Theme) => void;
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Navigation tabs
    home: 'Home',
    map: 'Map',
    contacts: 'Contacts',
    messages: 'Messages',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Log out',
    language: 'Language',
    appearance: 'Appearance',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    addContact: 'Add Contact',
    sendInvitation: 'Send',
    cancel: 'Cancel',
    accept: 'Accept',
    reject: 'Decline',
    noContacts: 'No contacts yet',
    noInvitations: 'No invitations yet',
    checkUpdates: 'Check for updates',
    appVersion: 'App version',
    invitationSent: 'Invitation sent!',
    alreadyInContacts: 'Already in contacts',
    duplicateInvitation: 'Invitation already pending',
    cancelInvitation: 'Cancel invitation',
    account: 'Account',
    app: 'App',
    chat: 'Chat',

    // Home tab (PortableInterfaceNew)
    welcome: 'Welcome',
    subtitleDriver: 'Start your day as a driver',
    subtitleUser: 'Find available drivers near you',
    location: 'Location',
    status: 'Status',
    visible: 'Visible',
    hidden: 'Hidden',
    quickActions: 'Quick Actions',
    refreshLocation: 'Refresh Location',
    viewMap: 'View Map',
    browseContacts: 'Browse Contacts',
    editProfile: 'Edit Profile',
    accuracy: 'Accuracy',
    alreadyHaveAccount: 'Already have an account? Sign in',
    dontHaveAccount: "Don't have an account? Sign up",

    // ProfileEditor
    tapAvatarToChange: 'Tap avatar to change photo',
    maxPhotoSize: 'Max 2 MB · compressed to 200×200',
    displayName: 'Display Name',
    usernameOptional: 'Username (optional)',
    usernameDesc: 'Your unique username for the platform',
    phoneOptional: 'Phone (optional)',
    bioOptional: 'Bio (optional)',
    bioMaxChars: 'Max 160 characters',
    accountType: 'Account Type',
    typeUser: 'User',
    typeDriver: 'Driver',
    visibility: 'Visibility',
    visibilityDesc: 'Make your profile visible to other users',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    photoUpdated: 'Photo updated successfully',
    photoError: 'Error uploading photo',
    profileUpdated: 'Profile updated successfully',
    profileError: 'Failed to update profile',
    selectImage: 'Select an image file',
    imageTooLarge: 'Image must be less than 2 MB',

    // ContactList
    searchContacts: 'Search contacts…',
    enterEmailOrPhone: 'Enter the email or phone number of the person you want to add.',
    emailOrPhone: 'Email or phone number',
    invitationsTab: 'Invitations',
    sentInvitations: 'Sent',
    receivedInvitations: 'Received',
    noContactsSearch: 'No contacts match your search',
    addFirstContact: '+ Add your first contact',
    removeContact: 'Remove contact?',
    removeContactDesc: 'will be removed from your contacts and you\'ll be removed from theirs. You can invite them again later.',
    remove: 'Remove',
    sendMessage: 'Send message',
    navigateHere: 'Navigate here',
    hideLocation: 'Hide my location',
    showLocation: 'Show my location',
    contactCount: 'contact',
    contactCountPlural: 'contacts',
    inMap: 'In map',

    // NavigationInterface
    navigating: 'Navigating',
    toDestination: 'Toward: ',
    distanceLabel: 'Distance',
    timeLabel: 'Time',
    endNavigation: 'End',
    calculating: 'Calculating route...',
    searchAddress: 'Search address or place...',
    startNavigation: 'Start Navigation',
    changeDestination: 'Change destination',
    chooseContact: 'or choose a contact',
    noContactsGPS: 'No contact has an active location.',
    noContactsGPSHint: 'Search an address above or wait for a contact to share their GPS.',
    waitingGPS: 'Waiting for GPS signal...',
    gpsActive: 'GPS Active',
    muteVoice: 'Disable voice',
    unmuteVoice: 'Enable voice',
    repeatInstruction: 'Repeat instruction',

    // GPSMapComponent
    gpsInactive: 'GPS Inactive',
    driversLabel: 'Drivers',
    usersLabel: 'Users',
    openGpsNav: 'Open GPS navigation',
    active: 'Active',
    inactive: 'Inactive',

    // ChatInterface
    selectContactToChat: 'Select a contact to start chatting',
    noMessagesYet: 'No messages yet',
    sendFirstMessage: 'Send the first message to start the conversation',
    searchConversation: 'Search in conversation...',
    typeMessage: 'Type a message...',
    online: 'Online',
    driverBadge: '🚗 Driver',
    userBadge: '👤 User',
    search: 'Search',

    // PWAUpdateNotification
    newVersion: '🆕 New version available',
    updateDescription: 'A new Urban Drive update is ready to install. Do you want to apply it now?',
    updateDescriptionLater: 'If you choose Later, the update will stay pending and you can apply it from Settings → Check for updates.',
    updateLater: 'Later',
    updateNow: 'Update now',

    // SettingsSheet
    updateAvailable: 'New version available',
    update: 'Update',
    lookingForUpdates: 'Looking for updates…',
    alreadyUpToDate: '✓ You already have the latest version',

    // Subscription plan display
    planFree: 'Free Plan',
    planBronce: 'Bronce',
    planPlata: 'Plata',
    planOro: 'Oro',
    planActive: 'Active plan',
    planChangePlan: 'Change plan',
    planUpgrade: 'Upgrade',
    planContactsLimit: 'contacts',

    // Contact limit
    contactLimitTitle: 'Contact Limit Reached',
    contactLimitDesc: 'You have reached the limit of {max} contacts on the {plan} plan. Upgrade to add more.',
    upgradePlan: 'Upgrade Plan',

    // Free-tier message limits
    msgLimitReached: 'Daily message limit reached. Upgrade to chat freely.',
    msgLimitRemaining: '{n} messages left today',

    // Free-tier active contact slot modal
    slotModalTitle: 'Your contact slot is full',
    slotModalDesc: '{name} wants to connect with you, but you already have an active contact.',
    slotCurrent: 'current',
    slotNew: 'new',
    slotHint: 'Paid contacts can always see you on the map, even if your slot is full.',
    slotUpgrade: 'Upgrade — see everyone',
    slotReplace: 'Replace with {name}',
    slotDecline: 'Decline new invitation',
    yourContact: 'Your contact',

    // Upgrade modal
    upgradeMsgLimitTitle: 'Daily limit reached',
    upgradeMsgLimitDesc: 'Free plan allows 2 messages per day per contact. Upgrade for unlimited messaging.',
    upgradeVoiceTitle: 'Voice notes — paid feature',
    upgradeVoiceDesc: 'Voice notes are available on the Bronce plan and above. Upgrade now.',
    upgradePlanBronce: 'What you get with Bronce',
    upgradeFeatureContacts: 'Up to 15 contacts',
    upgradeFeatureMsgs: 'Unlimited messages',
    upgradeFeatureVoice: 'Voice notes',
    upgradeFeatureMap: 'See all contacts on the map',

    // Voice notes plan gate
    voiceNotesLockedTitle: 'Voice notes require a paid plan',

    // Portal
    manageSubscription: 'Manage Subscription',
    openingPortal: 'Opening portal...',
    portalError: 'Could not open the subscription portal. Please try again.',
    // Post-payment success
    subscriptionActivated: 'Subscription activated!',
    subscriptionActivatedDesc: 'Welcome to the {plan} plan. Enjoy your new features.',
    subscriptionCanceled: 'Checkout canceled',
    // Contacts count with limit
    contactsOf: '{n} of {max}',

    // Enterprise — Company & Fleet
    myCompany: 'My Company',
    setupCompany: 'Set Up Company',
    manageFleet: 'Manage Fleet',
    manageDrivers: 'Manage Drivers',
    companyName: 'Company Name',
    legalName: 'Legal Name',
    taxId: 'Tax ID / NIT',
    transportModalities: 'Transport Modalities',
    noCompanyYet: 'No company registered yet',
    companyCreated: 'Company created!',
    companyUpdated: 'Company updated',
    addVehicle: 'Add Vehicle',
    editVehicle: 'Edit Vehicle',
    plate: 'Plate',
    makeModel: 'Make / Model',
    vehicleYear: 'Year',
    vehicleCategory: 'Category',
    vehicleFuelType: 'Fuel Type',
    passengerCapacity: 'Passenger Capacity',
    vehicleAdded: 'Vehicle added',
    vehicleUpdated: 'Vehicle updated',
    vehicleRemoved: 'Vehicle removed',
    fleetEmpty: 'No vehicles yet. Add your first vehicle.',
    addDriver: 'Add Driver',
    editDriver: 'Edit Driver',
    licenseNumber: 'License Number',
    licenseCategory: 'License Category',
    assignedVehicle: 'Assigned Vehicle',
    noVehicleAssigned: 'No vehicle assigned',
    driverAdded: 'Driver added',
    driverRemoved: 'Driver removed',
    driversEmpty: 'No drivers yet. Add your first driver.',
    companySetupTitle: 'Set Up Your Company',
    stepOf: 'Step {step} of {total}',
    enterpriseOnlyBronce: 'Available from Bronce plan',
    deleteVehicle: 'Delete Vehicle',
    deleteDriver: 'Delete Driver',
    confirmDelete: 'Are you sure? This action cannot be undone.',
    contactName: 'Contact Name',
    contactEmail: 'Contact Email',
    contactPhone: 'Contact Phone',
    description: 'Description',
    next: 'Next',
    previous: 'Previous',
    finish: 'Finish',
    make: 'Make',
    model: 'Model',

    // Enterprise — Maintenance
    maintenance: 'Maintenance',
    maintenanceLog: 'Maintenance Log',
    maintenanceScheduler: 'Maintenance Alerts',
    manageMaintenance: 'Maintenance Alerts',
    addMaintenance: 'Add Maintenance',
    editMaintenance: 'Edit Maintenance',
    maintenanceType: 'Type',
    maintenanceDate: 'Date',
    mileageAtService: 'Mileage at Service',
    nextServiceKm: 'Next Service (km)',
    nextServiceDate: 'Next Service (date)',
    workshopName: 'Workshop',
    technician: 'Technician',
    cost: 'Cost',
    maintenanceNotes: 'Notes',
    maintenanceAdded: 'Maintenance record added',
    maintenanceUpdated: 'Maintenance record updated',
    maintenanceRemoved: 'Maintenance record removed',
    maintenanceEmpty: 'No maintenance records yet.',
    statusOk: 'Up to date',
    statusWarning: 'Due soon',
    statusOverdue: 'Overdue',
    daysRemaining: '{n} days remaining',
    kmRemaining: '{n} km remaining',
    daysOverdue: '{n} days overdue',
    kmOverdue: '{n} km overdue',
    allUpToDate: 'All vehicles are up to date',

    // Enterprise — Documents
    documentVault: 'Documents',
    documentsDashboard: 'Documents Dashboard',
    manageDocuments: 'Documents Dashboard',
    companyDocuments: 'Company Documents',
    addDocument: 'Add',
    editDocument: 'Edit Document',
    deleteDocument: 'Delete Document',
    documentAdded: 'Document added',
    documentUpdated: 'Document updated',
    documentRemoved: 'Document removed',
    docIssueDate: 'Issue Date',
    docExpiryDate: 'Expiry Date',
    docFileURL: 'Document URL (optional)',
    docStatusValid: 'Valid',
    docStatusExpiring: 'Expiring soon',
    docStatusExpired: 'Expired',
    docStatusNoExpiry: 'No expiry',
    docMissing: 'Pending',
    viewDocument: 'View document',
    allDocsValid: 'All documents are valid',
    noDocumentsYet: 'No documents registered yet',

    // Enterprise — Fleet Analytics
    fleetAnalytics: 'Fleet Analytics',
    analyticsLockedTitle: 'Available from Plata plan',
    analyticsLockedDesc: 'Upgrade to unlock fleet analytics.',
    kpiActiveVehicles: 'Active Vehicles',
    kpiAssignedDrivers: 'Assigned Drivers',
    kpiMaintenanceCost: 'Maintenance Cost',
    kpiDocCompliance: 'Doc Compliance',
    maintenanceOverview: 'Maintenance Status',
    docComplianceOverview: 'Document Compliance',
    fleetCompositionLabel: 'Fleet Composition',
    costTrend: 'Cost Trend (6 months)',
    mileageByVehicle: 'Mileage by Vehicle',
    avgFleetMileage: 'Fleet Average',
    oroOnlyFeature: 'Available in Oro plan',
    noAnalyticsData: 'No data yet.',
    totalCostLabel: 'Total',

    // PricingPlans
    pricingTitle: 'Subscription Plans',
    pricingSubtitle: 'For individuals and businesses',
    billingMonthly: 'Monthly',
    billingYearly: 'Yearly',
    billingPerMonth: '/mo',
    billingYearlySave: '{total} billed yearly · save {saved}',
    planRecommended: 'Recommended',
    planTaglineBronce: 'Perfect for independent drivers',
    planTaglinePlata: 'Ideal for small and medium fleets',
    planTaglineOro: 'For large-scale operations',
    planCurrentCta: '✓ Current plan',
    planSubscribeTo: 'Subscribe to {plan}',
    planProcessing: 'Processing...',
    planNoCommitment: 'No commitments · Cancel anytime',
    planSecurePayments: 'Secure payments — Stripe · Bank transfer',

    // Payment methods
    bankTransferShort: 'Transfer',
    bankTransferTitle: 'Bank Transfer',
    bankTransferDesc: 'Transfer the exact amount and include the reference.',
    transferAmount: 'Amount to transfer',
    bankName: 'Bank',
    bankAccountName: 'Account name',
    bankAccountNumber: 'Account number',
    bankAccountType: 'Account type',
    bankRoutingCode: 'Routing / ABA',
    bankTransferRef: 'Reference (include in transfer)',
    bankTransferRefHint: 'You must include this reference so we can identify your payment.',
    transferDone: 'I already made the transfer',
    transferring: 'Confirming…',
    transferConfirmedTitle: 'Transfer registered!',
    transferConfirmedDesc: 'We received your notice with reference {ref}. We will activate your plan within 1 business day.',
    transferError: 'Could not register transfer',

    // Admin bank transfer activation
    adminActivateTransfer: 'Activate',
    adminActivateTransferTitle: 'Activate subscription',
    adminActivateTransferDesc: 'Confirm that the bank transfer was received and activate the subscription for this user.',
    adminActivateTransferRef: 'Reference',
    adminActivateTransferAmount: 'Amount',
    adminActivateTransferConfirm: 'Confirm and activate',
    adminActivateTransferSuccess: 'Subscription activated successfully',
    adminActivateTransferError: 'Error activating subscription',

    planCancelNote: 'To cancel or change plan, contact support.',
    planStripeNotConfigured: 'Stripe Price IDs are not yet configured.',
    featDrivers: 'Drivers',
    featModalities: 'Modalities',
    featActiveTrips: 'Active trips',
    featGPS: 'GPS tracking',
    featChat: 'Contact chat',
    featStats: 'Analytics',
    featAPI: 'REST API',
    featBranding: 'Custom branding',
    featSupport: 'Support',
    featUpTo: 'up to {n}',
    featUnlimited: 'Unlimited',
    featAll: 'All',
    featBasic: 'Basic',
    featAdvanced: 'Advanced',
    featPriorityEmail: 'Priority email',
    featPhoneEmail: 'Phone + Email',

    // Admin Portal
    adminPortal: 'Admin Portal',
    adminDashboard: 'Dashboard',
    adminUsers: 'Users',
    adminCompanies: 'Companies',
    adminSubscriptions: 'Subscriptions',
    adminFleet: 'Fleet',
    adminMaintenance: 'Maintenance',
    adminDocuments: 'Documents',
    adminTotalUsers: 'Total Users',
    adminTotalCompanies: 'Companies',
    adminMRR: 'Est. MRR',
    adminActiveSubs: 'Active Subs',
    adminAccessDenied: 'Access Denied',
    adminAccessDeniedDesc: 'Your account does not have admin privileges.',
    adminSearch: 'Search...',
    adminFilterByType: 'Filter by type',
    adminFilterByPlan: 'Filter by plan',
    adminFilterByStatus: 'Filter by status',
    adminRefresh: 'Refresh',
    adminNoData: 'No data available',

    // Discount coupons
    couponHave: 'Have a coupon?',
    couponCode: 'Coupon code',
    couponApply: 'Apply',
    couponInvalid: 'Invalid or expired coupon',
    couponApplied: 'Coupon applied!',
    coupon10Desc: '10% discount on your plan',
    coupon50Desc: '50% discount on your plan',
    coupon100Desc: '100% free — plan activated!',
    couponActivating: 'Activating plan…',
    couponActivated: 'Plan activated for free!',
    couponActivateError: 'Error activating plan. Please try again.',
    coupon10Label: '10% Off',
    coupon50Label: '50% Off',
    coupon100Label: '100% Free',
    adminCoupons: 'Coupons',
    couponGenerate: 'Generate Coupon',
    couponType: 'Discount type',
    couponNotes: 'Notes (optional)',
    couponCopy: 'Copy code',
    couponCopied: 'Copied!',
    couponCancelCoupon: 'Cancel coupon',
    couponCancelReason: 'Reason (optional)',
    couponExpires: 'Expires',
    couponUsedBy: 'Used by',
    couponGenerated: 'Coupon generated!',
    couponCancelled: 'Coupon cancelled',
    couponNoCoupons: 'No coupons yet',

    // Voice commands (Push-to-Talk)
    holdToTalk: 'Hold to talk',
    voiceListening: 'Listening…',
    voiceProcessing: 'Processing…',
    voiceError: 'Voice error. Try again.',
    voiceNotSupported: 'Voice commands not supported in this browser',
    voiceMicDenied: 'Microphone access denied',
    voiceNavigatingTo: 'Navigating to {name}',
    voiceContactNotFound: 'Contact not found',
    voiceSearching: 'Searching {name}',
    voiceOpeningChat: 'Opening chat with {name}',
    voiceStatusOnWay: 'On my way',
    voiceStatusArrived: 'I have arrived',

    // Voice notes (chat)
    voiceNoteLabel: 'Voice note',
    holdToRecord: 'Hold to record',
    voiceRecording: 'Recording…',
    voiceNoteSending: 'Sending…',
    voiceNoteError: 'Error sending voice note',
    voiceNoteUnsupported: 'Voice notes not supported in this browser',

    // Push notifications
    notificationsEnabled: 'Notifications enabled',
    notificationsDenied: 'Notifications blocked. Enable them in your browser settings.',
    newMessage: 'New message',
    deleteInvitation: 'Delete invitation',

    // General UI (enterprise)
    loading: 'Loading…',
    limitReached: 'Limit reached',
    fieldRequired: '{field} is required',
    errorSaving: 'Error saving',
    errorDeleting: 'Error deleting',
    activate: 'Activate',
    deactivate: 'Deactivate',
    delete: 'Delete',

    // Fleet / vehicles
    vehiclesLabel: 'vehicles',
    limitReachedVehicles: 'Vehicle limit of {max} reached. Upgrade your plan.',
    driverUpdated: 'Driver updated',
    limitReachedDrivers: 'Driver limit of {max} reached. Upgrade your plan.',
    noVehiclesAvailable: 'No vehicles available to assign',
    limitReachedModalities: 'Modality limit of {max} for your plan.',
    unlimitedModalities: 'Unlimited',
    maxN: 'max. {max}',
    nSelected: '{n} selected',
    maintenanceHint: 'Log maintenance from Fleet to activate alerts.',
    docsLabel: 'docs',
    docsValid: 'valid',
    docsExpiring: 'expiring soon',
    docsExpired: 'expired',

    // Conversations
    noConversations: 'No conversations',
    startChatFromContacts: 'Select a contact to start a chat',
    newChat: 'New chat',
    deleteConversation: 'Delete conversation',
    deleteConversationWith: 'Delete conversation with {name}?',
    deleteConversationDesc: 'All messages will be deleted',
    deleteMessage: 'Delete message',

    // Coupon
    couponDiscApplied: '{pct}% off applied',
  },
  es: {
    // Navigation tabs
    home: 'Inicio',
    map: 'Mapa',
    contacts: 'Contactos',
    messages: 'Mensajes',
    profile: 'Perfil',
    settings: 'Ajustes',
    logout: 'Cerrar sesión',
    language: 'Idioma',
    appearance: 'Apariencia',
    darkMode: 'Modo oscuro',
    lightMode: 'Modo claro',
    addContact: 'Añadir contacto',
    sendInvitation: 'Enviar',
    cancel: 'Cancelar',
    accept: 'Aceptar',
    reject: 'Rechazar',
    noContacts: 'Sin contactos aún',
    noInvitations: 'Sin invitaciones aún',
    checkUpdates: 'Buscar actualizaciones',
    appVersion: 'Versión de la app',
    invitationSent: '¡Invitación enviada!',
    alreadyInContacts: 'Ya está en tus contactos',
    duplicateInvitation: 'Invitación ya pendiente',
    cancelInvitation: 'Cancelar invitación',
    account: 'Cuenta',
    app: 'App',
    chat: 'Chat',

    // Home tab (PortableInterfaceNew)
    welcome: 'Bienvenido/a',
    subtitleDriver: 'Comienza tu jornada como conductor',
    subtitleUser: 'Encuentra conductores disponibles cerca de ti',
    location: 'Ubicación',
    status: 'Estado',
    visible: 'Visible',
    hidden: 'Oculto',
    quickActions: 'Acciones rápidas',
    refreshLocation: 'Actualizar ubicación',
    viewMap: 'Ver mapa',
    browseContacts: 'Ver contactos',
    editProfile: 'Editar perfil',
    accuracy: 'Precisión',
    alreadyHaveAccount: '¿Ya tienes cuenta? Inicia sesión',
    dontHaveAccount: '¿No tienes cuenta? Regístrate',

    // ProfileEditor
    tapAvatarToChange: 'Toca el avatar para cambiar foto',
    maxPhotoSize: 'Máx 2 MB · se comprime a 200×200',
    displayName: 'Nombre',
    usernameOptional: 'Nombre de usuario (opcional)',
    usernameDesc: 'Tu nombre de usuario único en la plataforma',
    phoneOptional: 'Teléfono (opcional)',
    bioOptional: 'Biografía (opcional)',
    bioMaxChars: 'Máx 160 caracteres',
    accountType: 'Tipo de cuenta',
    typeUser: 'Usuario',
    typeDriver: 'Conductor',
    visibility: 'Visibilidad',
    visibilityDesc: 'Haz tu perfil visible para otros usuarios',
    saving: 'Guardando...',
    saveChanges: 'Guardar cambios',
    photoUpdated: 'Foto actualizada correctamente',
    photoError: 'Error al subir la foto',
    profileUpdated: 'Perfil actualizado correctamente',
    profileError: 'Error al actualizar el perfil',
    selectImage: 'Selecciona un archivo de imagen',
    imageTooLarge: 'La imagen debe ser menor a 2 MB',

    // ContactList
    searchContacts: 'Buscar contactos…',
    enterEmailOrPhone: 'Ingresa el email o número de teléfono de la persona que quieres agregar.',
    emailOrPhone: 'Email o número de teléfono',
    invitationsTab: 'Invitaciones',
    sentInvitations: 'Enviadas',
    receivedInvitations: 'Recibidas',
    noContactsSearch: 'Ningún contacto coincide con tu búsqueda',
    addFirstContact: '+ Añade tu primer contacto',
    removeContact: '¿Eliminar contacto?',
    removeContactDesc: 'será eliminado de tus contactos y tú serás eliminado de los suyos. Puedes invitarlo de nuevo más tarde.',
    remove: 'Eliminar',
    sendMessage: 'Enviar mensaje',
    navigateHere: 'Navegar aquí',
    hideLocation: 'Ocultar mi ubicación',
    showLocation: 'Mostrar mi ubicación',
    contactCount: 'contacto',
    contactCountPlural: 'contactos',
    inMap: 'En mapa',

    // NavigationInterface
    navigating: 'Navegando',
    toDestination: 'Hacia: ',
    distanceLabel: 'Distancia',
    timeLabel: 'Tiempo',
    endNavigation: 'Finalizar',
    calculating: 'Calculando ruta...',
    searchAddress: 'Buscar dirección o lugar...',
    startNavigation: 'Iniciar Navegación',
    changeDestination: 'Cambiar destino',
    chooseContact: 'o elige un contacto',
    noContactsGPS: 'Ningún contacto tiene ubicación activa.',
    noContactsGPSHint: 'Busca una dirección arriba o espera a que un contacto comparta su GPS.',
    waitingGPS: 'Esperando señal GPS...',
    gpsActive: 'GPS Activo',
    muteVoice: 'Desactivar voz',
    unmuteVoice: 'Activar voz',
    repeatInstruction: 'Repetir instrucción',

    // GPSMapComponent
    gpsInactive: 'GPS Inactivo',
    driversLabel: 'Conductores',
    usersLabel: 'Usuarios',
    openGpsNav: 'Abrir navegación GPS',
    active: 'Activo',
    inactive: 'Inactivo',

    // ChatInterface
    selectContactToChat: 'Selecciona un contacto para chatear',
    noMessagesYet: 'Sin mensajes aún',
    sendFirstMessage: 'Envía el primer mensaje para iniciar la conversación',
    searchConversation: 'Buscar en la conversación...',
    typeMessage: 'Escribe un mensaje...',
    online: 'En línea',
    driverBadge: '🚗 Conductor',
    userBadge: '👤 Usuario',
    search: 'Buscar',

    // PWAUpdateNotification
    newVersion: '🆕 Nueva versión disponible',
    updateDescription: 'Hay una actualización de Urban Drive lista para instalarse. ¿Quieres aplicarla ahora?',
    updateDescriptionLater: 'Si eliges Más tarde, la actualización quedará pendiente y podrás aplicarla desde Ajustes → Buscar actualizaciones.',
    updateLater: 'Más tarde',
    updateNow: 'Actualizar ahora',

    // SettingsSheet
    updateAvailable: 'Nueva versión disponible',
    update: 'Actualizar',
    lookingForUpdates: 'Buscando actualizaciones…',
    alreadyUpToDate: '✓ Ya tienes la última versión',

    // Subscription plan display
    planFree: 'Plan Gratuito',
    planBronce: 'Bronce',
    planPlata: 'Plata',
    planOro: 'Oro',
    planActive: 'Plan activo',
    planChangePlan: 'Cambiar plan',
    planUpgrade: 'Mejorar plan',
    planContactsLimit: 'contactos',

    // Contact limit
    contactLimitTitle: 'Límite de contactos alcanzado',
    contactLimitDesc: 'Has alcanzado el límite de {max} contactos del plan {plan}. Actualiza tu plan para agregar más.',
    upgradePlan: 'Actualizar plan',

    // Free-tier message limits
    msgLimitReached: 'Límite diario alcanzado. Actualiza tu plan para chatear sin límites.',
    msgLimitRemaining: '{n} mensajes restantes hoy',

    // Free-tier active contact slot modal
    slotModalTitle: 'Tu espacio de contacto está ocupado',
    slotModalDesc: '{name} quiere conectarse contigo, pero ya tienes un contacto activo.',
    slotCurrent: 'actual',
    slotNew: 'nuevo',
    slotHint: 'Los contactos con plan pago siempre pueden verte en el mapa, aunque tu espacio esté lleno.',
    slotUpgrade: 'Actualizar — ver a todos',
    slotReplace: 'Reemplazar por {name}',
    slotDecline: 'Rechazar nueva invitación',
    yourContact: 'Tu contacto',

    // Upgrade modal
    upgradeMsgLimitTitle: 'Límite diario alcanzado',
    upgradeMsgLimitDesc: 'El plan gratuito permite 2 mensajes por día por contacto. Actualiza para mensajes ilimitados.',
    upgradeVoiceTitle: 'Notas de voz — función de pago',
    upgradeVoiceDesc: 'Las notas de voz están disponibles en el plan Bronce y superiores.',
    upgradePlanBronce: 'Qué obtienes con Bronce',
    upgradeFeatureContacts: 'Hasta 15 contactos',
    upgradeFeatureMsgs: 'Mensajes ilimitados',
    upgradeFeatureVoice: 'Notas de voz',
    upgradeFeatureMap: 'Ver todos tus contactos en el mapa',

    // Voice notes plan gate
    voiceNotesLockedTitle: 'Las notas de voz requieren un plan de pago',

    // Portal
    manageSubscription: 'Gestionar suscripción',
    openingPortal: 'Abriendo portal...',
    portalError: 'No se pudo abrir el portal de suscripción. Por favor intenta de nuevo.',
    // Post-payment success
    subscriptionActivated: '¡Suscripción activada!',
    subscriptionActivatedDesc: 'Bienvenido al plan {plan}. Disfruta tus nuevas funciones.',
    subscriptionCanceled: 'Pago cancelado',
    // Contacts count with limit
    contactsOf: '{n} de {max}',

    // Enterprise — Empresa y Flota
    myCompany: 'Mi Empresa',
    setupCompany: 'Configurar Empresa',
    manageFleet: 'Gestionar Flota',
    manageDrivers: 'Gestionar Conductores',
    companyName: 'Nombre de la Empresa',
    legalName: 'Razón Social',
    taxId: 'NIT / RUT',
    transportModalities: 'Modalidades de Transporte',
    noCompanyYet: 'Aún no tienes empresa registrada',
    companyCreated: '¡Empresa creada!',
    companyUpdated: 'Empresa actualizada',
    addVehicle: 'Agregar Vehículo',
    editVehicle: 'Editar Vehículo',
    plate: 'Placa',
    makeModel: 'Marca / Modelo',
    vehicleYear: 'Año',
    vehicleCategory: 'Categoría',
    vehicleFuelType: 'Combustible',
    passengerCapacity: 'Capacidad de Pasajeros',
    vehicleAdded: 'Vehículo agregado',
    vehicleUpdated: 'Vehículo actualizado',
    vehicleRemoved: 'Vehículo eliminado',
    fleetEmpty: 'Sin vehículos. Agrega tu primer vehículo.',
    addDriver: 'Agregar Conductor',
    editDriver: 'Editar Conductor',
    licenseNumber: 'Número de Licencia',
    licenseCategory: 'Categoría de Licencia',
    assignedVehicle: 'Vehículo Asignado',
    noVehicleAssigned: 'Sin vehículo asignado',
    driverAdded: 'Conductor agregado',
    driverRemoved: 'Conductor eliminado',
    driversEmpty: 'Sin conductores. Agrega tu primer conductor.',
    companySetupTitle: 'Configura Tu Empresa',
    stepOf: 'Paso {step} de {total}',
    enterpriseOnlyBronce: 'Disponible desde el plan Bronce',
    deleteVehicle: 'Eliminar Vehículo',
    deleteDriver: 'Eliminar Conductor',
    confirmDelete: '¿Estás seguro? Esta acción no se puede deshacer.',
    contactName: 'Nombre de Contacto',
    contactEmail: 'Email de Contacto',
    contactPhone: 'Teléfono de Contacto',
    description: 'Descripción',
    next: 'Siguiente',
    previous: 'Anterior',
    finish: 'Finalizar',
    make: 'Marca',
    model: 'Modelo',

    // Enterprise — Mantenimiento
    maintenance: 'Mantenimiento',
    maintenanceLog: 'Historial de Mantenimiento',
    maintenanceScheduler: 'Alertas de Mantenimiento',
    manageMaintenance: 'Alertas de Mantenimiento',
    addMaintenance: 'Registrar Mantenimiento',
    editMaintenance: 'Editar Mantenimiento',
    maintenanceType: 'Tipo',
    maintenanceDate: 'Fecha',
    mileageAtService: 'Kilometraje al servicio',
    nextServiceKm: 'Próximo servicio (km)',
    nextServiceDate: 'Próximo servicio (fecha)',
    workshopName: 'Taller',
    technician: 'Técnico',
    cost: 'Costo',
    maintenanceNotes: 'Notas',
    maintenanceAdded: 'Mantenimiento registrado',
    maintenanceUpdated: 'Mantenimiento actualizado',
    maintenanceRemoved: 'Registro eliminado',
    maintenanceEmpty: 'Sin registros de mantenimiento.',
    statusOk: 'Al día',
    statusWarning: 'Próximo',
    statusOverdue: 'Vencido',
    daysRemaining: '{n} días restantes',
    kmRemaining: '{n} km restantes',
    daysOverdue: '{n} días vencido',
    kmOverdue: '{n} km vencido',
    allUpToDate: 'Todos los vehículos están al día',

    // Enterprise — Documentos
    documentVault: 'Documentos',
    documentsDashboard: 'Panel de Documentos',
    manageDocuments: 'Panel de Documentos',
    companyDocuments: 'Documentos de Empresa',
    addDocument: 'Agregar',
    editDocument: 'Editar Documento',
    deleteDocument: 'Eliminar Documento',
    documentAdded: 'Documento agregado',
    documentUpdated: 'Documento actualizado',
    documentRemoved: 'Documento eliminado',
    docIssueDate: 'Fecha de emisión',
    docExpiryDate: 'Fecha de vencimiento',
    docFileURL: 'URL del documento (opcional)',
    docStatusValid: 'Vigente',
    docStatusExpiring: 'Por vencer',
    docStatusExpired: 'Vencido',
    docStatusNoExpiry: 'Sin vencimiento',
    docMissing: 'Pendiente',
    viewDocument: 'Ver documento',
    allDocsValid: 'Todos los documentos están vigentes',
    noDocumentsYet: 'Sin documentos registrados aún',

    // Enterprise — Analíticas de Flota
    fleetAnalytics: 'Analíticas de Flota',
    analyticsLockedTitle: 'Disponible desde el plan Plata',
    analyticsLockedDesc: 'Actualiza para desbloquear analíticas.',
    kpiActiveVehicles: 'Vehículos activos',
    kpiAssignedDrivers: 'Conductores asignados',
    kpiMaintenanceCost: 'Costo de mantenimiento',
    kpiDocCompliance: 'Cumplimiento documental',
    maintenanceOverview: 'Estado de mantenimiento',
    docComplianceOverview: 'Cumplimiento de documentos',
    fleetCompositionLabel: 'Composición de flota',
    costTrend: 'Tendencia de costos (6 meses)',
    mileageByVehicle: 'Kilometraje por vehículo',
    avgFleetMileage: 'Promedio de flota',
    oroOnlyFeature: 'Disponible en plan Oro',
    noAnalyticsData: 'Sin datos aún.',
    totalCostLabel: 'Total',

    // PricingPlans
    pricingTitle: 'Planes de suscripción',
    pricingSubtitle: 'Para personas naturales y empresas',
    billingMonthly: 'Mensual',
    billingYearly: 'Anual',
    billingPerMonth: '/mes',
    billingYearlySave: '{total} facturado anualmente · ahorras {saved}',
    planRecommended: 'Recomendado',
    planTaglineBronce: 'Perfecto para conductores independientes',
    planTaglinePlata: 'Ideal para flotas pequeñas y medianas',
    planTaglineOro: 'Para operaciones de gran escala',
    planCurrentCta: '✓ Plan actual',
    planSubscribeTo: 'Suscribirse a {plan}',
    planProcessing: 'Procesando...',
    planNoCommitment: 'Sin compromisos · Cancela cuando quieras',
    planSecurePayments: 'Pagos seguros — Stripe · Transferencia bancaria',

    // Payment methods
    bankTransferShort: 'Transferencia',
    bankTransferTitle: 'Transferencia Bancaria',
    bankTransferDesc: 'Transfiere el monto exacto e incluye la referencia en el concepto.',
    transferAmount: 'Monto a transferir',
    bankName: 'Banco',
    bankAccountName: 'Titular de la cuenta',
    bankAccountNumber: 'Número de cuenta',
    bankAccountType: 'Tipo de cuenta',
    bankRoutingCode: 'Código de ruta / ABA',
    bankTransferRef: 'Referencia (incluir en la transferencia)',
    bankTransferRefHint: 'Debes incluir esta referencia para que podamos identificar tu pago.',
    transferDone: 'Ya realicé la transferencia',
    transferring: 'Confirmando…',
    transferConfirmedTitle: '¡Transferencia registrada!',
    transferConfirmedDesc: 'Recibimos tu aviso con la referencia {ref}. Activaremos tu plan en máximo 1 día hábil.',
    transferError: 'No se pudo registrar la transferencia',

    // Admin activación de transferencia bancaria
    adminActivateTransfer: 'Activar',
    adminActivateTransferTitle: 'Activar suscripción',
    adminActivateTransferDesc: 'Confirma que la transferencia bancaria fue recibida y activa la suscripción para este usuario.',
    adminActivateTransferRef: 'Referencia',
    adminActivateTransferAmount: 'Monto',
    adminActivateTransferConfirm: 'Confirmar y activar',
    adminActivateTransferSuccess: 'Suscripción activada exitosamente',
    adminActivateTransferError: 'Error al activar la suscripción',

    planCancelNote: 'Para cancelar o cambiar de plan, contacta soporte.',
    planStripeNotConfigured: 'Los Price IDs de Stripe aún no han sido configurados.',
    featDrivers: 'Conductores',
    featModalities: 'Modalidades',
    featActiveTrips: 'Viajes activos',
    featGPS: 'Seguimiento GPS',
    featChat: 'Chat con contactos',
    featStats: 'Estadísticas',
    featAPI: 'API REST',
    featBranding: 'Marca personalizada',
    featSupport: 'Soporte',
    featUpTo: 'hasta {n}',
    featUnlimited: 'Ilimitados',
    featAll: 'Todas',
    featBasic: 'Básicas',
    featAdvanced: 'Avanzadas',
    featPriorityEmail: 'Email prioritario',
    featPhoneEmail: 'Teléfono + Email',

    // Admin Portal
    adminPortal: 'Portal Admin',
    adminDashboard: 'Panel',
    adminUsers: 'Usuarios',
    adminCompanies: 'Empresas',
    adminSubscriptions: 'Suscripciones',
    adminFleet: 'Flota',
    adminMaintenance: 'Mantenimiento',
    adminDocuments: 'Documentos',
    adminTotalUsers: 'Usuarios totales',
    adminTotalCompanies: 'Empresas',
    adminMRR: 'MRR estimado',
    adminActiveSubs: 'Subs activas',
    adminAccessDenied: 'Acceso denegado',
    adminAccessDeniedDesc: 'Tu cuenta no tiene privilegios de administrador.',
    adminSearch: 'Buscar...',
    adminFilterByType: 'Filtrar por tipo',
    adminFilterByPlan: 'Filtrar por plan',
    adminFilterByStatus: 'Filtrar por estado',
    adminRefresh: 'Actualizar',
    adminNoData: 'Sin datos disponibles',

    // Cupones de descuento
    couponHave: '¿Tienes un cupón?',
    couponCode: 'Código de cupón',
    couponApply: 'Aplicar',
    couponInvalid: 'Cupón inválido o expirado',
    couponApplied: '¡Cupón aplicado!',
    coupon10Desc: '10% de descuento en tu plan',
    coupon50Desc: '50% de descuento en tu plan',
    coupon100Desc: '100% gratis — ¡plan activado!',
    couponActivating: 'Activando plan…',
    couponActivated: '¡Plan activado gratis!',
    couponActivateError: 'Error al activar el plan. Intenta de nuevo.',
    coupon10Label: '10% Desc.',
    coupon50Label: '50% Desc.',
    coupon100Label: '100% Gratis',
    adminCoupons: 'Cupones',
    couponGenerate: 'Generar Cupón',
    couponType: 'Tipo de descuento',
    couponNotes: 'Notas (opcional)',
    couponCopy: 'Copiar código',
    couponCopied: '¡Copiado!',
    couponCancelCoupon: 'Cancelar cupón',
    couponCancelReason: 'Razón (opcional)',
    couponExpires: 'Vence',
    couponUsedBy: 'Usado por',
    couponGenerated: '¡Cupón generado!',
    couponCancelled: 'Cupón cancelado',
    couponNoCoupons: 'Sin cupones aún',

    // Comandos de voz (Push-to-Talk)
    holdToTalk: 'Mantén para hablar',
    voiceListening: 'Escuchando…',
    voiceProcessing: 'Procesando…',
    voiceError: 'Error de voz. Intenta de nuevo.',
    voiceNotSupported: 'Comandos de voz no soportados en este navegador',
    voiceMicDenied: 'Acceso al micrófono denegado',
    voiceNavigatingTo: 'Navegando hacia {name}',
    voiceContactNotFound: 'Contacto no encontrado',
    voiceSearching: 'Buscando {name}',
    voiceOpeningChat: 'Abriendo chat con {name}',
    voiceStatusOnWay: 'En camino',
    voiceStatusArrived: 'He llegado',

    // Notas de voz (chat)
    voiceNoteLabel: 'Nota de voz',
    holdToRecord: 'Mantén para grabar',
    voiceRecording: 'Grabando…',
    voiceNoteSending: 'Enviando…',
    voiceNoteError: 'Error al enviar nota de voz',
    voiceNoteUnsupported: 'Notas de voz no soportadas en este navegador',

    // Notificaciones push
    notificationsEnabled: 'Notificaciones activadas',
    notificationsDenied: 'Notificaciones bloqueadas. Actívalas en la configuración del navegador.',
    newMessage: 'Nuevo mensaje',
    deleteInvitation: 'Eliminar invitación',

    // General UI (empresa)
    loading: 'Cargando…',
    limitReached: 'Límite alcanzado',
    fieldRequired: '{field} es requerido',
    errorSaving: 'Error al guardar',
    errorDeleting: 'Error al eliminar',
    activate: 'Activar',
    deactivate: 'Desactivar',
    delete: 'Eliminar',

    // Flota / vehículos
    vehiclesLabel: 'vehículos',
    limitReachedVehicles: 'Límite de {max} vehículos alcanzado. Actualiza tu plan.',
    driverUpdated: 'Conductor actualizado',
    limitReachedDrivers: 'Límite de {max} conductores alcanzado. Actualiza tu plan.',
    noVehiclesAvailable: 'Sin vehículos disponibles para asignar',
    limitReachedModalities: 'Límite de {max} modalidad(es) para tu plan.',
    unlimitedModalities: 'Ilimitadas',
    maxN: 'máx. {max}',
    nSelected: '{n} seleccionadas',
    maintenanceHint: 'Registra mantenimientos desde la Flota para activar alertas.',
    docsLabel: 'docs',
    docsValid: 'válidos',
    docsExpiring: 'por vencer',
    docsExpired: 'vencidos',

    // Conversaciones
    noConversations: 'Sin conversaciones',
    startChatFromContacts: 'Selecciona un contacto para iniciar un chat',
    newChat: 'Nuevo chat',
    deleteConversation: 'Eliminar conversación',
    deleteConversationWith: '¿Eliminar conversación con {name}?',
    deleteConversationDesc: 'Se borrarán todos los mensajes',
    deleteMessage: 'Eliminar mensaje',

    // Cupón
    couponDiscApplied: '{pct}% de descuento aplicado',
  },
};

const AppContext = createContext<AppContextValue | null>(null);

function detectLang(): Lang {
  const stored = localStorage.getItem('lang') as Lang | null;
  if (stored === 'en' || stored === 'es') return stored;
  return navigator.language.startsWith('es') ? 'es' : 'en';
}

function detectTheme(): Theme {
  const stored = localStorage.getItem('theme') as Theme | null;
  if (stored === 'dark' || stored === 'light') return stored;
  return 'dark';
}

export function AppProvider({ children }: { children: React.ReactNode }) {
  const [theme, setThemeState] = useState<Theme>(detectTheme);
  const [lang, setLangState] = useState<Lang>(detectLang);

  useEffect(() => {
    const root = document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
    localStorage.setItem('theme', theme);
  }, [theme]);

  const setTheme = (t: Theme) => {
    setThemeState(t);
  };

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('lang', l);
  };

  const t = (key: string): string => {
    return translations[lang][key] ?? key;
  };

  return (
    <AppContext.Provider value={{ theme, setTheme, lang, setLang, t }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp(): AppContextValue {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used inside AppProvider');
  return ctx;
}
